package nobugs.team.shopping.repo.db.entity;

import java.util.List;
import de.greenrobot.dao.DaoException;
import nobugs.team.shopping.repo.db.DaoSession;
import nobugs.team.shopping.repo.db.dao.ProductDao;
import nobugs.team.shopping.repo.db.dao.ShopDao;
import nobugs.team.shopping.repo.db.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SHOP.
 */
public class ShopPo {

    private Integer id;
    private String name;
    private String introduction;
    private Integer ownerid;
    private Integer productid;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ShopDao myDao;

    private UserPo userPo;
    private Integer user__resolvedKey;

    private List<ProductPo> productPoList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ShopPo() {
    }

    public ShopPo(Integer id) {
        this.id = id;
    }

    public ShopPo(Integer id, String name, String introduction, Integer ownerid, Integer productid) {
        this.id = id;
        this.name = name;
        this.introduction = introduction;
        this.ownerid = ownerid;
        this.productid = productid;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getShopDao() : null;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public Integer getOwnerid() {
        return ownerid;
    }

    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    public Integer getProductid() {
        return productid;
    }

    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /** To-one relationship, resolved on first access. */
    public UserPo getUserPo() {
        Integer __key = this.ownerid;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            UserPo userPoNew = targetDao.load(__key);
            synchronized (this) {
                userPo = userPoNew;
            	user__resolvedKey = __key;
            }
        }
        return userPo;
    }

    public void setUserPo(UserPo userPo) {
        synchronized (this) {
            this.userPo = userPo;
            ownerid = userPo == null ? null : userPo.getId();
            user__resolvedKey = ownerid;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ProductPo> getProductPoList() {
        if (productPoList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ProductDao targetDao = daoSession.getProductDao();
            List<ProductPo> productPoListNew = targetDao._queryShop_ProductList(id);
            synchronized (this) {
                if(productPoList == null) {
                    productPoList = productPoListNew;
                }
            }
        }
        return productPoList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetProductList() {
        productPoList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
