package nobugs.team.shopping.repo.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table USER.
 */
public class UserPo {

    private Integer id;
    private String name;
    private String password;
    private String phone;
    private Integer type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserPo() {
    }

    public UserPo(Integer id) {
        this.id = id;
    }

    public UserPo(Integer id, String name, String password, String phone, Integer type) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.phone = phone;
        this.type = type;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public boolean isSeller(){
        return type == 2;
    }
}
