package nobugs.team.shopping.repo.api.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import nobugs.team.shopping.repo.api.db.dao.UserDao;
import nobugs.team.shopping.repo.model.UserPo;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userPoDaoConfig;

    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userPoDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userPoDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userPoDaoConfig, this);

        registerDao(UserPo.class, userDao);
    }
    
    public void clear() {
        userPoDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
